import bcrypt from 'bcryptjs';

const data = {
	users: [
		{
			name: 'Kevin LeRoy',
			email: 'admin@example.com',
			password: bcrypt.hashSync('1234', 10),
			isAdmin: true,
		},
		{
			name: 'John Doe',
			email: 'jdoe@example.com',
			password: bcrypt.hashSync('1234', 10),
			isAdmin: false,
		},
	],
	products: [
		{
			name: 'Nike Slim Shirt',
			category: 'Shirts',
			image: '/images/p1.jpg',
			price: 120,
			countInStock: 10,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 10,
			description: 'high quality product',
		},
		{
			name: 'Adidas Slim Shirt',
			category: 'Shirts',
			image: '/images/p2.jpg',
			price: 100,
			countInStock: 20,
			brand: 'Adidas',
			rating: 4.5,
			numReviews: 10,
			description: 'high quality product',
		},
		{
			name: 'Lacoste Free Shirt',
			category: 'Shirts',
			image: '/images/p3.jpg',
			price: 220,
			countInStock: 0,
			brand: 'Lascoste',
			rating: 4.8,
			numReviews: 17,
			description: 'high quality product',
		},
		{
			name: 'Nike Slim Pant',
			category: 'Pants',
			image: '/images/p4.jpg',
			price: 78,
			countInStock: 15,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 14,
			description: 'high quality product',
		},
		{
			name: 'Puma Slim Pant',
			category: 'Pants',
			image: '/images/p5.jpg',
			price: 65,
			countInStock: 5,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 10,
			description: 'high quality product',
		},
		{
			name: 'Adidas Slim Pant',
			category: 'Pants',
			image: '/images/p6.jpg',
			price: 139,
			countInStock: 12,
			brand: 'Adidas',
			rating: 4.5,
			numReviews: 10,
			description: 'high quality product',
		},
	],
};

export default data;
